"""empty message

Revision ID: 3eb68bf2303e
Revises: cd12d61eae4b
Create Date: 2025-02-28 17:59:22.532737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb68bf2303e'
down_revision = 'cd12d61eae4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed', sa.Integer(), nullable=True, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('processed')

    # ### end Alembic commands ###
