"""empty message

Revision ID: 718f45539aad
Revises: 3eb68bf2303e
Create Date: 2025-06-28 15:25:37.312617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718f45539aad'
down_revision = '3eb68bf2303e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_uploaded', sa.DateTime(), nullable=False, server_default="2025-01-01 00:00:01.000001"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('processed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.alter_column('processed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('datetime_uploaded')

    # ### end Alembic commands ###
