"""empty message

Revision ID: d070ba45f215
Revises: 718f45539aad
Create Date: 2025-10-04 16:53:33.569570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd070ba45f215'
down_revision = '718f45539aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('published')
        batch_op.drop_column('user_secret')

    # ### end Alembic commands ###
